CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    email_address TEXT NOT NULL,
    role TEXT NOT NULL
);

INSERT INTO users (id, username, "password", email_address, "role")
VALUES
    (1, 'admin', 'admin', 'powerupsoup@gmail.com', 'dungeon_master');