CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    email_address TEXT NOT NULL,
    role TEXT NOT NULL
);

INSERT INTO users (id, username, "password", email_address, "role")
VALUES
    (1, 'admin', 'admin', 'powerupsoup@gmail.com', 'dungeon_master'),
    (2, 'player1', 'player1', 'seanajackson1989@gmail.com', 'player'),
    (3, 'player2', 'player2', 'irenemstaffordlmt@gmail.com', 'player');
  